# Car Driding Risk Analysis with Multiple Features using Linear Regression

In [18]:
#Importing Library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [19]:
#Importing Dataset
df = pd.read_csv('Car Driving Risk Analysis Multiple Features.csv')

In [20]:
df

speed  car_age  driver_experience  risk
0     200     10.0                4.0    95
1      90     12.0                5.0    20
2     300     15.0                2.0    98
3     110      5.0                3.0    60
4     240      4.0                NaN    72
5     115      3.0                6.0    10
6      50      6.0                6.0     7
7     230      NaN                2.0    85
8     190     10.0                3.0    45
9     260      8.0                5.0    91
10    290     12.0                1.0    82
11    185     20.0                7.0    59
12    310     18.0                8.0    93
13     95      1.0               10.0    18
14     30      3.0               12.0     2

In [42]:
df.shape

(15, 4)

In [21]:
#Checking Null Values
df.isnull().sum()

speed                0
car_age              1
driver_experience    1
risk                 0
dtype: int64

In [22]:
#Showing values from different column
df.car_age

0     10.0
1     12.0
2     15.0
3      5.0
4      4.0
5      3.0
6      6.0
7      NaN
8     10.0
9      8.0
10    12.0
11    20.0
12    18.0
13     1.0
14     3.0
Name: car_age, dtype: float64

# Null Value Handling

In [26]:
median_value_car = df.car_age.median()
median_value_driver_experience = df.driver_experience.median()

In [34]:
df.car_age = df.car_age.fillna(median_value_car)

In [35]:
df.driver_experience = df.driver_experience.fillna(median_value_driver_experience)

In [37]:
#Updated DataSet
df

speed  car_age  driver_experience  risk
0     200     10.0                4.0    95
1      90     12.0                5.0    20
2     300     15.0                2.0    98
3     110      5.0                3.0    60
4     240      4.0                5.0    72
5     115      3.0                6.0    10
6      50      6.0                6.0     7
7     230      9.0                2.0    85
8     190     10.0                3.0    45
9     260      8.0                5.0    91
10    290     12.0                1.0    82
11    185     20.0                7.0    59
12    310     18.0                8.0    93
13     95      1.0               10.0    18
14     30      3.0               12.0     2

# Dividing Columns into Features and Class

In [38]:
x = df[['speed', 'car_age', 'driver_experience']]
y = df['risk']

In [39]:
x

speed  car_age  driver_experience
0     200     10.0                4.0
1      90     12.0                5.0
2     300     15.0                2.0
3     110      5.0                3.0
4     240      4.0                5.0
5     115      3.0                6.0
6      50      6.0                6.0
7     230      9.0                2.0
8     190     10.0                3.0
9     260      8.0                5.0
10    290     12.0                1.0
11    185     20.0                7.0
12    310     18.0                8.0
13     95      1.0               10.0
14     30      3.0               12.0

In [40]:
y

0     95
1     20
2     98
3     60
4     72
5     10
6      7
7     85
8     45
9     91
10    82
11    59
12    93
13    18
14     2
Name: risk, dtype: int64

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = .25, random_state = 1)

In [47]:
xtrain

speed  car_age  driver_experience
10    290     12.0                1.0
4     240      4.0                5.0
1      90     12.0                5.0
13     95      1.0               10.0
0     200     10.0                4.0
14     30      3.0               12.0
9     260      8.0                5.0
8     190     10.0                3.0
12    310     18.0                8.0
11    185     20.0                7.0
5     115      3.0                6.0

In [48]:
ytrain

10    82
4     72
1     20
13    18
0     95
14     2
9     91
8     45
12    93
11    59
5     10
Name: risk, dtype: int64

# Building Linear Model

In [51]:
from sklearn.linear_model import LinearRegression

In [52]:
lr = LinearRegression()

# Training the model

In [ ]:
lr.fit(xtrain, ytrain)

# Predicting values

In [56]:
lr.predict(xtest)

array([25.71766355, 69.62738465,  5.22486857, 96.63699326])

In [61]:
lr.predict([[150, 4, 3]])

array([39.57765807])

# Finding coefficient and intercept
y = m1(speed) + m2(car_age) + m3(driver_experience) + c

In [62]:
lr.coef_

array([0.35538573, 0.35543461, 0.1583047 ])

In [63]:
#c
lr.intercept_

-15.626853694585414

# Performance Calculating

In [65]:
lr.score(xtest, ytest)

0.7080970998792983