# Male Female Prediction using Decision Tree

In [232]:
#Importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import tree

In [233]:
#Importing Dataset
df = pd.read_csv('dataset of male female.csv')

In [234]:
#Showing Read Dataset
df

height  weight  shoe size  gender
0      181      80         44    male
1      177      70         43  female
2      160      60         38  female
3      154      54         37  female
4      166      65         40    male
5      190      90         47    male
6      175      64         39    male
7      171      75         42  female
8      185      85         43  female
9      169      71         42    male
10     180      75         43    male
11     160      60         35  female
12     190      85         50    male
13     140      60         30  female

In [235]:
df.isnull().sum()

height       0
weight       0
shoe size    0
gender       0
dtype: int64

In [236]:
df.shape

(14, 4)

# Decision Tree Applying

In [237]:
x = df.iloc[:, :-1]

In [238]:
x

height  weight  shoe size
0      181      80         44
1      177      70         43
2      160      60         38
3      154      54         37
4      166      65         40
5      190      90         47
6      175      64         39
7      171      75         42
8      185      85         43
9      169      71         42
10     180      75         43
11     160      60         35
12     190      85         50
13     140      60         30

In [239]:
y = df.iloc[:, 3]

In [240]:
y

0       male
1     female
2     female
3     female
4       male
5       male
6       male
7     female
8     female
9       male
10      male
11    female
12      male
13    female
Name: gender, dtype: object

In [241]:
#Making Classifier
dt = tree.DecisionTreeClassifier()

In [242]:
dt.fit(x, y)

DecisionTreeClassifier()

In [243]:
dt.predict([[160, 70, 40]])

array(['male'], dtype=object)

# SPliting Dataset into Train and Testing

In [244]:
from sklearn.model_selection import train_test_split

In [245]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = .20, random_state = 1)

In [246]:
dt2 = tree.DecisionTreeClassifier()

In [247]:
dt2.fit(xtrain, ytrain)

DecisionTreeClassifier()

In [248]:
prediction = dt2.predict(xtest)

In [249]:
dt2.predict([[160, 40, 30]])

array(['female'], dtype=object)

# Accuracy Calculating

In [250]:
from sklearn.metrics import accuracy_score

In [251]:
score = accuracy_score(ytest, prediction)

In [252]:
print ('Accuracy is:', score * 100, '%')

Accuracy is: 33.33333333333333 %


In [253]:
from sklearn.metrics import confusion_matrix

In [254]:
confusion_matrix(ytest, prediction)

array([[1, 1],
       [1, 0]], dtype=int64)

In [255]:
from sklearn.metrics import classification_report

In [256]:
cr = classification_report(ytest, prediction)

In [257]:
print (cr) #Classification Report

              precision    recall  f1-score   support

      female       0.50      0.50      0.50         2
        male       0.00      0.00      0.00         1

    accuracy                           0.33         3
   macro avg       0.25      0.25      0.25         3
weighted avg       0.33      0.33      0.33         3



# Trying to Applying Linear Regression

In [258]:
from sklearn import preprocessing

In [259]:
pr = preprocessing.LabelEncoder()

In [261]:
pr.fit(df['gender'])

LabelEncoder()

In [262]:
le = pr.transform(df['gender'])

In [263]:
le

array([1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0])

In [264]:
from sklearn.model_selection import train_test_split

In [265]:
xtrain, xtest, ytrain, ytest = train_test_split(x, le, test_size = .20, random_state = 1)

In [266]:
xtrain

height  weight  shoe size
2      160      60         38
10     180      75         43
4      166      65         40
1      177      70         43
12     190      85         50
0      181      80         44
13     140      60         30
9      169      71         42
8      185      85         43
11     160      60         35
5      190      90         47

In [267]:
from sklearn.linear_model import LinearRegression

In [268]:
lr = LinearRegression()

In [269]:
lr.fit(xtrain, ytrain)

LinearRegression()

In [270]:
lr.predict(xtest)

array([ 0.43160344,  0.75946036, -0.10164858])